In [3]:
print(f" H0: μ = 25, H1: μ ≠ 25  is True since assumption behind hypothesis testing is to equate parameters in null hypothesis which is being followed")
print (f"H0: σ > 10, H1: σ = 10  is False since assumption behind hypothesis testing is to equate parameters in null hypothesis which is not being followed")
print (f"H0: x = 50, H1: x ≠ 50 is True with assumption that mu is also 50 and hence they are assuming x  = mean as condition for null hypothesis")
print (f" H0: p = 0.1, H1: p = 0.5 - I cannot decide based on the info") 
print(f"5. H0: s = 30, H1: s > 30, is True since they are equating in null hypothesis")

 H0: μ = 25, H1: μ ≠ 25  is True since assumption behind hypothesis testing is to equate parameters in null hypothesis which is being followed
H0: σ > 10, H1: σ = 10  is False since assumption behind hypothesis testing is to equate parameters in null hypothesis which is not being followed
H0: x = 50, H1: x ≠ 50 is True with assumption that mu is also 50 and hence they are assuming x  = mean as condition for null hypothesis
 H0: p = 0.1, H1: p = 0.5 - I cannot decide based on the info
5. H0: s = 30, H1: s > 30, is True since they are equating in null hypothesis


In [1]:
import numpy as np
from scipy import stats

In [2]:
def z_value(x,mu,std,n):
    return (x-mu)/(std/(n**(1/2)))

# Problem Statement 2

In [32]:
p = stats.norm.cdf(z_value(52.8,52,4.5,100))
print("the probability is: ", p)
if p > 0.05:
    print("null hypothesis accepted, the price is not higher than Rs 52")
else:
    print("null hypothesis rejected")

the probability is:  0.9622798201865993
null hypothesis accepted, the price is not higher than Rs 52


# Problem Statement 3

In [33]:
p = stats.norm.cdf(z_value(32.5,34,8,50))
print("the probability is: ", p)
if p > 0.01:
    print("null hypothesis accepted, the price is not higher than Rs 52")
else:
    print("null hypothesis rejected")

the probability is:  0.0924487994828001
null hypothesis accepted, the price is not higher than Rs 52


# Problem Statement 4

In [65]:
s = [1008, 812, 1117, 1323, 1308, 1415, 831, 1021, 1287, 851, 930, 730, 699,872, 913, 944, 954, 987, 1695, 995, 1003, 994]
mu = 1135   #population mean 
t_value = (np.mean(s) - mu) /( np.std(s)  / (22**(1/2)))
print("the T value is: ", t_value)
if abs(t_value) < stats.t.ppf(.975,21):                  # use confidence level as .975 as it is a two tailed test
    print("null hypothesis is accepted, the numbers are accurate")
else:
    print("null hypothesis is rejected")

the T value is:  -2.070747228595759
null hypothesis is accepted, the numbers are accurate


# Problem Statement 5

In [5]:
# null hypothesis , x at $48,574 = mu of $48,432
score = z_value(48574, 48432,2000,400)
print("the z score is: ", score)
if score < 1.96:
    print("null hypothesis is accepted, the average annual family income is correctly published")
else:
    print("null hypothesis is rejected")

the z score is:  1.42
null hypothesis is accepted, the average annual family income is correctly published


# Problem Statement 6

In [7]:
def t_value(x,mu,std,n):
    return (x-mu)/(std/(n**(1/2)))

In [14]:
print('null hypothesis , x at $31.67 = mu of $32.28 where mu is population mean')
print('the alternate hypothesis is the sample mean has changed over from past population mean.')
score = t_value(31.67,32.28,1.29,19)
print("the T value is: ", score)
if abs(score) < stats.t.ppf(1-.05/2,19-1):                  # use confidence level as .975 as it is a two tailed test
    print("null hypothesis is accepted, the past avg price per square foot numbers are accurate")
else:
    print("null hypothesis is rejected")

null hypothesis , x at $31.67 = mu of $32.28 where mu is population mean
the alternate hypothesis is the sample mean has changed over from past population mean.
the T value is:  -2.06118477175179
null hypothesis is accepted, the past avg price per square foot numbers are accurate


# Problem Statement 7

In [ ]:
# assuming alpha to be 5%
n = 10
mu = 52


# Problem Statement 8

In [16]:
print(f'the t score for the given parameters is : {t_value(12,10,1.5,16)}')

the t score for the given parameters is : 5.333333333333333


# Problem Statement 9

In [19]:
print(f'the t score for required parameters is :{stats.t.ppf(1-.99,16-1)}')

the t score for required parameters is :-2.602480294995493


# Problem Statement 10

In [37]:
print(f'the t score for middle 95% sample is : +- {stats.t.ppf(1-.975,25-1)}')

the t score for middle 95% sample is : +- -2.0638985616280205


In [39]:
print(f'the probability for (−t0.05 <t<t0.10) is :{1-.05-.10}')   #as p(t<-0.05 is .05 left of t and p(t<0.10 ) is entire area except right of 0.10)

the probability for (−t0.05 <t<t0.10) is :0.85


In [33]:
# Problem Statement 11

In [58]:
def z_twosample(x1,s1,n1,x2,s2,n2):
    return (x1-x2) / ((((s1**2)/n1) + ((s2**2)/n2))**(1/2))


In [72]:
# null hypothesis is x1 = x2
# alternate hypothesis is x1 != x2
score = z_twosample(452,212,1200,523,185,800)
print(f'the z value for the two samples is:', score)
if abs(score) < abs(stats.t.ppf(1-.975,1200+800-2)):
    print('null hypothesis is accepted, there is enough evidence to prove the mean no. of travellers is same for both destinations')
else:
    print("null hypothesis is rejected")

the z value for the two samples is: -7.926428526759299
null hypothesis is rejected


In [21]:
# Problem Statement 12

In [71]:
# null hypothesis is x1 = x2
# alternate hypothesis is x1 != x2
score = z_twosample(308,84,100,254,67,100)
print(f'the z value for the two samples is:', score)
if abs(score) < abs(stats.t.ppf(1-.975,100+100-2)):
    print('null hypothesis is accepted, there is enough evidence to prove the mean no. of people preferring both batteries are same')
else:
    print("null hypothesis is rejected")

the z value for the two samples is: 5.025702668336442
null hypothesis is rejected


In [22]:
# Problem Statement 13

In [80]:
def t_twosample(x1,s1,n1,x2,s2,n2):       # when population size < 30
    return (x1-x2) / (( (((n1-1)*(s1**2))+((n2-1)*(s2**2)))/(n1+n2-2) *( (1/n1)+(1/n2) ))**(1/2))


In [81]:
# null hypothesis is x1 = x2
# alternate hypothesis is x1 != x2
score = t_twosample(.317,.12,14,.21,.11,9)
print(f'the z value for the two samples is:', score)
if abs(score) < abs(stats.t.ppf(1-.975,14+9-2)):
    print('null hypothesis is accepted, there is enough evidence to conclude that average percentage increase in the price of sugar does not differs')
else:
    print("null hypothesis is rejected")

the z value for the two samples is: 2.15355322387416
null hypothesis is rejected


In [23]:
# Problem Statement 14

In [85]:
# null hypothesis is x1 = x2
# alternate hypothesis is x1 != x2
score = t_twosample(6870,669,12,6598,844,15)
print(f'the z value for the two samples is:', score)
if abs(score) < abs(stats.t.ppf(1-.95,12+15-2)):
    print('null hypothesis is accepted, there is enough evidence to prove reducing price can improve sales')
else:
    print("null hypothesis is rejected")

the z value for the two samples is: 0.9098300343990461
null hypothesis is accepted, there is enough evidence to prove reducing price can improve sales


In [25]:
# Problem Statement 15

In [123]:
def p_value (x1,p1,n1,x2,p2,n2,D):
    p3 = (x1+x2)/(n1+n2)
    return (p1-p2)/((p3*(1-p3)*((1/n1)+(1/n2)))**(1/2)) 

In [125]:
score = p_value(53,0.53,100,43,0.43,100,0)
print('the p value for the given details is: ',score)
if abs(stats.norm.cdf(score)) < abs(stats.norm.ppf(.025)):
    print('null hypothesis is accepted, there is enough evidence to prove two proportions are not different')
else:
    print("null hypothesis is rejected")

the p value for the given details is:  1.4153462926807452
null hypothesis is accepted, there is enough evidence to prove two proportions are not different


In [26]:
# Problem Statement 16

In [126]:
score = p_value(120,0.4,300,140,0.2,700,.1)
print('the p value for the given details is: ',score)
if abs(stats.norm.cdf(score)) < abs(stats.norm.ppf(.05)):
    print('null hypothesis is accepted, there is enough evidence to prove two proportions are not different')
else:
    print("null hypothesis is rejected")

the p value for the given details is:  6.607499047222304
null hypothesis is accepted, there is enough evidence to prove two proportions are not different


In [91]:
# Problem Statement 17

In [88]:
# there are equal chances of getting 1-6 when rolling the dice and hence expected outcome is same for all = 132/6 = 22
chi , p = stats.chisquare([16, 20, 25, 14, 29, 28],[22,22,22,22,22,22])
print (f'the chi and p values are:', chi, p)
if chi < stats.chi2.ppf(1-.05,5):
    print('null hypothesis is accepted, there is enough evidence to prove die is unbiased')
else:
    print("null hypothesis is rejected")

the chi and p values are: 9.0 0.1090641579497725
null hypothesis is accepted, there is enough evidence to prove die is unbiased


In [28]:
# Problem Statement 18

In [117]:
# city's population for men and women is (2792+1486) and (3591+2131) = 4278 and 5722
# as there are equal chances for men and women to vote, expected no.s should be 50% of the voted for each.
Voted = [2792,3591]  
Non_voted = [1486,2131]
Total = [4278,5722]
Expected = []
j =[]
for i in Total:
    Expected.append((i/10000)*sum(Voted))
    j.append((i/10000)*sum(Non_voted))
chi , p = stats.chisquare((Voted + Non_voted),(Expected +j))
print (f'the chi and p values are:', chi, p)
if chi < stats.chi2.ppf(1-.01,((2-1)*(2-1))):
    print('null hypothesis is accepted, there is enough evidence to prove voting and gender are independent')
else:
    print("null hypothesis is rejected")


the chi and p values are: 6.660455899328019 0.08354483102552486
null hypothesis is rejected


In [29]:
# Problem Statement 19

In [91]:
chi , p = stats.chisquare([41,19,24,16],[25,25,25,25])
print (f'the chi and p values are:', chi, p)
if chi < stats.chi2.ppf(1-.05,3):
    print('null hypothesis is accepted, there is enough evidence to prove voting and gender are independent')
else:
    print("null hypothesis is rejected")

the chi and p values are: 14.959999999999999 0.001851152735284203
null hypothesis is rejected


In [30]:
# Problem Statement 20

In [121]:
chi,p, df, expected = stats.chi2_contingency([[18,22,20],[2,28,40],[20,10,40]])
print('the result of chisquare are',chi,p, df, expected)
if chi < stats.chi2.ppf(1-.05,4):
    print('null hypothesis is accepted, there is enough evidence to prove signigicance between age and photo preference')
else:
    print("null hypothesis is rejected")


the result of chisquare are 29.603174603174608 5.894582174262606e-06 4 [[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
null hypothesis is rejected


In [31]:
# Problem Statement 21

In [2]:
chi,p, df, expected = stats.chi2_contingency([[18,40],[32,10]])
print('the result of chisquare are',chi,p, df, expected)
if chi < stats.chi2.ppf(1-.05,1):
    print('null hypothesis is accepted, there is enough evidence to prove signigicance between age and photo preference')
else:
    print("null hypothesis is rejected")


the result of chisquare are 18.10344827586207 2.092221924065813e-05 1 [[29. 29.]
 [21. 21.]]
null hypothesis is rejected


In [32]:
# Problem Statement 22

In [4]:
chi,p, df, expected = stats.chi2_contingency([[12,32],[22,14],[9,6]])
print('the result of chisquare are',chi,p, df, expected)
if chi < stats.chi2.ppf(1-.01,2):
    print('null hypothesis is accepted, there is enough evidence to prove there a relationship between height and leadership qualities?')
else:
    print("null hypothesis is rejected")


the result of chisquare are 10.712198008709638 0.004719280137040844 2 [[19.91578947 24.08421053]
 [16.29473684 19.70526316]
 [ 6.78947368  8.21052632]]
null hypothesis is rejected


In [5]:
# Problem Statement 23

In [6]:
chi,p, df, expected = stats.chi2_contingency([[679,103,114],[63,10,20],[42,18,25]])
print('the result of chisquare are',chi,p, df, expected)
if chi < stats.chi2.ppf(1-.01,2):
    print('null hypothesis is accepted, there is enough evidence to prove there a relationship between height and leadership qualities?')
else:
    print("null hypothesis is rejected")


the result of chisquare are 31.61310319407798 2.2949883042859918e-06 4 [[654.06331471 109.2886406  132.64804469]
 [ 67.88826816  11.34357542  13.76815642]
 [ 62.04841713  10.36778399  12.58379888]]
null hypothesis is rejected
